# Generated by Django 4.0.4 on 2022-05-09 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('france', '0002_rename_scens_scenes_word_phrase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('scenes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='france.scenes')),
            ],
            options={
                'ordering': ('scenes',),
            },
        ),
    ]
