# Generated by Django 4.0.4 on 2022-05-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('france', '0003_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenes',
            name='scene_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
