# Generated by Django 4.0.4 on 2022-05-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('france', '0004_scenes_scene_image_delete_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenes',
            name='scene_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
